### ISSUE TITLE
Better handling of errors

### ISSUE THREAD

**Issue by stdevPavelmc** [daxslab/cuba-weather#24]
If the location is not found the user get's an error (exception dump) and then the important sentence get buried on the exception...

The user must see only the human targeted code, nor the full exception; aka we must catch the exception and replace it with a custom string and stop the processing.

**Comment by stdevPavelmc** [comment]
This is the actual behaviour:
```
pavel@agatha2:~/Documentos/Software/Github/cuba-weather$ ./weather.py "Camagüeys"
Traceback (most recent call last):
  File "./weather.py", line 49, in main
    c = RCApiClient(args.location)
  File "./weather.py", line 18, in __init__
    response = urllib.request.urlopen(url)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./weather.py", line 72, in <module>
    main()
  File "./weather.py", line 51, in main
    raise Exception('Location not found' if ex.code == 404 else ex)
Exception: Location not found
pavel@agatha2:~/Documentos/Software/Github/cuba-weather$
```

The logic dictates  that it must behave lake this or so...:

```
pavel@agatha2:~/Documentos/Software/Github/cuba-weather$ ./weather.py "Camagüeys"
Location not found, try checking your ortography or "Ciudad de" [location]
pavel@agatha2:~/Documentos/Software/Github/cuba-weather$ 
pavel@agatha2:~/Documentos/Software/Github/cuba-weather$ ./weather.py "Camagüey"
Cielo despejado
Temperature: 18.05°C
Humidity: 79%
Pressure: 1020 hpa
pavel@agatha2:~/Documentos/Software/Github/cuba-weather$ ./weather.py "Camagüeys"
Location not found, try checking your orthography.
pavel@agatha2:~/Documentos/Software/Github/cuba-weather$ ./weather.py "Florida"
Cielo despejado
Temperature: 18.05°C
Humidity: 79%
Pressure: 1020 hpa
pavel@agatha2:~/Documentos/Software/Github/cuba-weather$ ./weather.py "La Vallita"
Location not found, try checking your orthography.
pavel@agatha2:~/Documentos/Software/Github/cuba-weather$ ./weather.py "Sola"
Location not found, try checking your orthography.
pavel@agatha2:~/Documentos/Software/Github/cuba-weather$ ./weather.py "Paso de lezca"
Location not found, try checking your orthography.
pavel@agatha2:~/Documentos/Software/Github/cuba-weather$ ./weather.py "Paso de Lezca"
Location not found, try checking your orthography.
pavel@agatha2:~/Documentos/Software/Github/cuba-weather$ ./weather.py "Esmeralda"
Nublado
Temperature: 19.18°C
Humidity: 65%
Pressure: 1020 hpa
pavel@agatha2:~/Documentos/Software/Github/cuba-weather$
```
